Repository NASA-AMMOS/aerie-docs, pull requests merged in 2023-09, with the labels that each got.

#78 Add Permissions Docs
  docs/deployment/advanced-permissions.mdx
  sidebars.js
Labels: documentation

#80 Permissions Docs Pt. 2
  docs/deployment/advanced-permissions.mdx
Labels: documentation

#81 Upgrade deps to latest
  package-lock.json
  package.json
Labels: build

#83 Release v1.13.0
  docs/upgrade-guides/1-12-0-to-1-13-0.md
  sidebars.js
Labels: release
